Laboratório Analise de Vendas - Pandas

In [1]:
# Trabalha com DataFrames (Tabelas) e Séries (Colunas)
import pandas as pd

In [2]:
# Importação dos arquivos CSV
orders = pd.read_csv("https://raw.githubusercontent.com/marcosroquerosa/datasets/refs/heads/main/olist_dataset_reduzido/olist_orders_dataset.csv")
order_items = pd.read_csv("https://github.com/marcosroquerosa/datasets/raw/refs/heads/main/olist_dataset_reduzido/olist_order_items_dataset.csv")
customers = pd.read_csv("https://github.com/marcosroquerosa/datasets/raw/refs/heads/main/olist_dataset_reduzido/olist_customers_dataset.csv")
products = pd.read_csv("https://github.com/marcosroquerosa/datasets/raw/refs/heads/main/olist_dataset_reduzido/olist_products_dataset.csv")
sellers = pd.read_csv("https://github.com/marcosroquerosa/datasets/raw/refs/heads/main/olist_dataset_reduzido/olist_sellers_dataset.csv")

In [3]:
# Visualização do cabeçalho da tabela pedidos 5 primeiros registros
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,b9a6c5f5df52c7226ac85aee7524c27f,f160aaf480efdfa7268f0fa535f73e76,delivered,2018-06-12 20:07:44,2018-06-12 20:44:26,2018-06-13 13:09:00,2018-06-19 12:44:08,2018-07-17 00:00:00
1,261e71d2349c713eafa9f3df5972b95d,d6708bbbd2d419475869a84e41f620a1,delivered,2018-01-20 12:15:57,2018-01-20 12:37:13,2018-01-25 21:42:52,2018-01-30 11:32:35,2018-02-15 00:00:00
2,67b50899f52995848c427e361e10dde3,1b353c00c71689afba44554e43cc5a76,delivered,2018-06-16 21:24:10,2018-06-16 21:36:59,2018-06-21 13:55:00,2018-06-27 13:17:27,2018-07-16 00:00:00
3,32733fc014b67ef70fa6039dd8c6ba82,ad66699beab381d0747605f108cc02b4,delivered,2017-08-30 21:12:28,2017-08-31 02:50:24,2017-09-12 20:16:46,2017-09-25 17:53:23,2017-09-22 00:00:00
4,39a70e9e9b729b11dee34ac12478597f,20c678bfce3c8252288f70dd2bee5e51,delivered,2017-08-10 21:26:25,2017-08-10 21:44:13,2017-08-11 19:11:16,2017-08-22 16:45:00,2017-09-12 00:00:00

In [5]:
# Visualização dos 5 ultimos registros
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
4995,a4efbda58af31645539bafc75617196a,6035ab6f7cf530e8bc5d557c4ba1a6a2,delivered,2017-12-11 16:45:58,2017-12-13 16:39:26,2017-12-19 22:17:08,2017-12-22 14:25:17,2018-01-04 00:00:00
4996,e1f19495005161ca887eeb4b7cf3332d,074b92f6fc71f14f11bfa7c664136c8e,delivered,2017-02-11 20:02:31,2017-02-15 11:32:01,2017-02-20 15:58:50,2017-03-24 15:03:49,2017-04-07 00:00:00
4997,26499163fd30a5493b2e498337e9e2a7,d42fc1b5243a68aa0735371148f2cde8,delivered,2017-07-06 12:43:38,2017-07-08 03:25:27,2017-07-10 19:52:20,2017-07-18 20:23:19,2017-08-01 00:00:00
4998,ab292f6c11a661dd97feca37ffe7b162,d0ce4181898b96b8fc24e7c5c48c9761,delivered,2018-04-07 14:42:53,2018-04-07 14:55:09,2018-04-09 21:36:48,2018-04-10 23:32:21,2018-04-19 00:00:00
4999,d5ba4800b58a75d721450cb4ce724015,410b9be6153ea16cfc4ae635785aafe8,delivered,2018-03-26 15:54:38,2018-03-26 16:08:27,2018-03-27 19:12:08,2018-03-28 20:11:00,2018-04-06 00:00:00

In [7]:
orders.size

40000

In [16]:
# Visualizo as colunas e os tipos de dados de cada coluna.
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [11]:
order_items.size

39984

In [12]:
# PROCV - ORDERS e da ORDER_ITEMS
# order_id, customer_id, data_pedido, status
dados_tratados = order_items.merge(orders[['order_id', 'order_purchase_timestamp',
                                           'order_status', 'customer_id']], on='order_id', how='left')
# merge é o PROCV
# how='left' mantem todas as linhas da tabela principal

In [14]:
dados_tratados.dtypes

order_id                     object
order_item_id                 int64
product_id                   object
seller_id                    object
shipping_limit_date          object
price                       float64
freight_value               float64
order_purchase_timestamp     object
order_status                 object
customer_id                  object
dtype: object

In [17]:
dados_tratados.rename(columns={"order_purchase_timestamp":"data_pedido", "order_status":"status"}, inplace=True)

In [19]:
dados_tratados.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'data_pedido',
       'status', 'customer_id'],
      dtype='object')

In [20]:
# Adicionar o estado do cliente - procv trouxe o estado
dados_tratados = dados_tratados.merge(
    customers[['customer_id', 'customer_state']], on='customer_id', how='left'
)

In [21]:
dados_tratados.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'data_pedido',
       'status', 'customer_id', 'customer_state'],
      dtype='object')

In [22]:
# Categoria do Produto - procv - categoria
# product_id	product_category_name
dados_tratados = dados_tratados.merge(
    products[['product_id','product_category_name']],
    on='product_id',
    how='left'
)

In [24]:
dados_tratados.dtypes

order_id                  object
order_item_id              int64
product_id                object
seller_id                 object
shipping_limit_date       object
price                    float64
freight_value            float64
data_pedido               object
status                    object
customer_id               object
customer_state            object
product_category_name     object
dtype: object

In [25]:
# Transformamos a data do pedido em formato datatiem
dados_tratados['data_pedido'] = pd.to_datetime(dados_tratados['data_pedido'])
dados_tratados.dtypes

order_id                         object
order_item_id                     int64
product_id                       object
seller_id                        object
shipping_limit_date              object
price                           float64
freight_value                   float64
data_pedido              datetime64[ns]
status                           object
customer_id                      object
customer_state                   object
product_category_name            object
dtype: object

In [27]:
dados_tratados['mes'] = dados_tratados['data_pedido'].dt.month
dados_tratados['ano'] = dados_tratados['data_pedido'].dt.year
dados_tratados['mes_ano'] = dados_tratados['data_pedido'].dt.strftime('%m/%Y')

In [28]:
dados_tratados.dtypes

order_id                         object
order_item_id                     int64
product_id                       object
seller_id                        object
shipping_limit_date              object
price                           float64
freight_value                   float64
data_pedido              datetime64[ns]
status                           object
customer_id                      object
customer_state                   object
product_category_name            object
mes                               int32
ano                               int32
mes_ano                          object
dtype: object

In [36]:
# Pedidos Válidos, atribui sim ou não.
# Inicialmente -Não para todos,
# posterior localização e atribuição de valor "Sim"
dados_tratados['pedido_valido'] = 'Não'
dados_tratados.loc[dados_tratados['status'] == 'delivered', 'pedido_valido'] = 'Sim'

In [29]:
# Receita (preço + frete)
dados_tratados['receita'] = dados_tratados['price'] + dados_tratados['freight_value']

In [30]:
dados_tratados.dtypes

order_id                         object
order_item_id                     int64
product_id                       object
seller_id                        object
shipping_limit_date              object
price                           float64
freight_value                   float64
data_pedido              datetime64[ns]
status                           object
customer_id                      object
customer_state                   object
product_category_name            object
mes                               int32
ano                               int32
mes_ano                          object
receita                         float64
dtype: object

In [32]:
dados_tratados.drop(columns=['order_item_id', 'shipping_limit_date', ], inplace=True)
dados_tratados.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'freight_value',
       'data_pedido', 'status', 'customer_id', 'customer_state',
       'product_category_name', 'mes', 'ano', 'mes_ano', 'receita'],
      dtype='object')

In [33]:
dados_tratados.rename(columns={"product_category_name":"categoria", "customer_state":"estado_cliente"}, inplace=True)

In [37]:
dados_tratados.columns

Index(['order_id', 'product_id', 'seller_id', 'price', 'freight_value',
       'data_pedido', 'status', 'customer_id', 'estado_cliente', 'categoria',
       'mes', 'ano', 'mes_ano', 'receita', 'pedido_valido'],
      dtype='object')

In [38]:
# Reordenou as colunas do dataframe.

dados_tratados = dados_tratados[['order_id',
                                 'data_pedido',
                                 'status',
                                 'ano',
                                 'mes',
                                 'mes_ano',
                                 'pedido_valido',
                                 'customer_id',
                                 'estado_cliente',
                                 'product_id',
                                 'categoria',
                                 'seller_id',
                                 'price',
                                 'freight_value',
                                 'receita']]

In [39]:
dados_tratados.columns

Index(['order_id', 'data_pedido', 'status', 'ano', 'mes', 'mes_ano',
       'pedido_valido', 'customer_id', 'estado_cliente', 'product_id',
       'categoria', 'seller_id', 'price', 'freight_value', 'receita'],
      dtype='object')

In [40]:
# Output da tabela para um arquivo CSV
dados_tratados.to_csv('dados_tratados.csv', index=False)

In [41]:
# Limpeza de Dados
# Remover dados nulos
print(dados_tratados.size)
dados_tratados.dropna()
print(dados_tratados.size)

85680
85680

In [42]:
# Verificar registros duplicados
dados_tratados.duplicated().sum()

np.int64(574)

In [43]:
# Remove itens duplicados
dados_tratados = dados_tratados.drop_duplicates()

In [44]:
dados_tratados.size

77070

In [45]:
# Criar os KPIs
# Criar um novo dataframe somente com os pedidos válidos
validos = dados_tratados[dados_tratados['pedido_valido'] == 'Sim']
validos

,order_id,data_pedido,status,ano,mes,mes_ano,pedido_valido,customer_id,estado_cliente,product_id,categoria,seller_id,price,freight_value,receita
0,00259a44fcad3fc0474329e925d14fc3,2017-12-27 17:52:11,delivered,2017,12,12/2017,Sim,7715f80f77f2ebf4583f97a0a6a7548b,MG,0c4d0a08f95c7b7dc5dc7402bfdafd4c,informatica_acessorios,9f505651f4a6abe901a56cdc21508025,19.99,14.10,34.09
1,00275bce676303c3bfd7292aefdfa223,2017-11-24 23:10:30,delivered,2017,11,11/2017,Sim,a12427487c970a4a75dbeb5884f126a8,SP,6490b9f63b0b595e1c1402b46b0f50ad,telefonia,99eaacc9e6046db1c82b163c5f84869f,279.90,13.46,293.36
2,003edccf16bc5ec447f592913b3df2b4,2018-07-07 09:02:51,delivered,2018,7,07/2018,Sim,ab3642244247c0c638253fe68ee4c345,MA,500870614ddcf5bd84f7d26861026c8a,telefonia,ef506c96320abeedfb894c34db06f478,14.00,50.85,64.85
3,00471463a6106056c1a2a809f70de640,2017-09-21 22:00:44,delivered,2017,9,09/2017,Sim,fcad74a7e0dff27c33e36cbd78280bf9,DF,9df0e8a7eef2a38b74e6d5c0e224b11f,moveis_decoracao,7c67e1448b00f6e969d365cea6b010ab,179.99,85.97,265.96
4,0064d74f7de7917d54768d7722ad56ac,2017-09-10 21:45:29,delivered,2017,9,09/2017,Sim,29dbee0c474f373b72267a9e886522ee,RJ,fa11ecd35f999783e96ac500532d9d45,cool_stuff,2e90cb1677d35cfe24eef47d441b7c87,189.90,31.17,221.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5707,ffb8f7de8940249a3221252818937ecb,2018-07-22 12:58:25,delivered,2018,7,07/2018,Sim,036a2b2e7d16c12b97890ea51a2ef172,GO,803f77475e1b51b47f1bfec4f2ec353f,automotivo,c9c7905cffc4ef9ff9f113554423e671,79.99,6.37,86.36
5708,ffb8f7de8940249a3221252818937ecb,2018-07-22 12:58:25,delivered,2018,7,07/2018,Sim,036a2b2e7d16c12b97890ea51a2ef172,GO,bd0ac51dc93e62c4dbe6ca9d70a9b311,automotivo,1d4587203296c8f4ad134dc286fa6db0,64.50,42.47,106.97
5709,ffd5efbd46bbf72ad374862a05ef4c72,2017-02-01 18:39:14,delivered,2017,2,02/2017,Sim,486d66df3ef703d001f77632e7fe6bd8,MG,8338cef8355d238f43711dcb9c0657b2,moveis_decoracao,cca3071e3e9bb7d12640c9fbe2301306,45.90,14.52,60.42
5710,ffdda91cd98d69f6be1cd352e4447b8e,2018-06-03 13:43:44,delivered,2018,6,06/2018,Sim,b9b441696ae97a6a6d884f8240949ab7,DF,1ec486885049bbb9b79351d150ed18c4,fashion_bolsas_e_acessorios,cab85505710c7cb9b720bceb52b01cee,49.90,15.23,65.13
5711,ffea79d8c5fecc22cbff0c54eda9b65c,2017-09-03 17:18:58,delivered,2017,9,09/2017,Sim,bbef00095c712ca0e62584d68cb9fdfa,BA,ea44caac707f7f1325182a538007f838,bebes,855668e0971d4dfd7bef1b6a4133b41b,50.00,19.59,69.59

In [58]:
# Receita Total
receita_total = validos['receita'].sum()
print(f"Receita Total: R$ {receita_total:.2f}".replace(".",","))

Receita Total: R$ 722590,29

In [48]:
# Total de Pedidos
total_pedidos = validos['order_id'].nunique() # Contabiliza somente dados únicos, descarta repetidos)
print("Total de Pedidos: ", total_pedidos)

Total de Pedidos:  4854

In [59]:
# Ticket Médio
ticket_medio = receita_total / total_pedidos
print(f"Ticket Médio: R${ticket_medio:.2f}".replace(".",","))

Ticket Médio: R$148,86

In [60]:
# Clientes Únicos
clientes_unicos = validos['customer_id'].nunique()
print("Clientes únicos: ", clientes_unicos)

Clientes únicos:  4854

In [62]:
# Receita Média por cliente
receita_media_cliente = receita_total / clientes_unicos
print(f"Receita Média por cliente: R${receita_media_cliente:.2f}".replace(".",","))

Receita Média por cliente: R$148,86

In [63]:
# Total de Itens Vendidos
total_itens = validos['product_id'].nunique()
print("Total de itens únicos vendidos: ", total_itens)

Total de itens únicos vendidos:  3761

In [64]:
# groupby - Agrupa receita por categoria, descendente, somente 5 primeiros
# KPI Receita por Categoria (Top 5)
top_categoria = (validos.groupby('categoria')['receita']
                 .sum() # Somar todos os itens de uma categoria
                 .sort_values(ascending=False)
                 .head(5)
                 )
top_categoria

categoria
relogios_presentes        65825.01
beleza_saude              62533.99
cama_mesa_banho           56248.62
informatica_acessorios    50852.95
esporte_lazer             48183.80
Name: receita, dtype: float64

In [65]:
# Receita por Estado (Top 5)
top_estado = (validos.groupby('estado_cliente')['receita']
                 .sum() # Somar todos os itens de uma categoria
                 .sort_values(ascending=False)
                 .head(5)
                 )
top_estado

estado_cliente
SP    264853.49
RJ     97204.90
MG     87615.26
RS     43004.01
PR     34807.40
Name: receita, dtype: float64

In [66]:
# Receita por Vendedor (Top 5)
top_vendedor = (validos.groupby('seller_id')['receita']
                 .sum() # Somar todos os itens de uma categoria
                 .sort_values(ascending=False)
                 .head(5)
                 )
top_vendedor

seller_id
4a3ca9315b744ce9f8e9374361493884    12616.25
4869f7a5dfa277a7dca6462dcf3b52b2    12154.16
fa1c13f2614d7b5c4749cbc52fecda94    11610.92
7e93a43ef30c4f03f38b393420bc753a    10626.79
53243585a1d6dc2643021fd1853d8905     9740.11
Name: receita, dtype: float64

In [70]:
# Receita por Mês e Ano (Tendência)
receita_mes = (validos.groupby(['ano', 'mes'])['receita']
                 .sum() # Somar todos os itens de uma categoria
                 .reset_index()
                 .sort_values(['ano', 'mes'])
                 )
receita_mes

     ano  mes   receita
0   2016   10   2097.64
1   2017    1   5027.67
2   2017    2   9473.58
3   2017    3  25153.77
4   2017    4  18119.38
5   2017    5  23151.18
6   2017    6  26044.67
7   2017    7  27579.68
8   2017    8  32595.76
9   2017    9  27969.33
10  2017   10  33937.19
11  2017   11  49199.09
12  2017   12  39069.70
13  2018    1  52377.37
14  2018    2  43368.86
15  2018    3  53675.68
16  2018    4  54012.93
17  2018    5  59838.74
18  2018    6  44201.92
19  2018    7  43567.85
20  2018    8  52128.30

In [73]:
# Receita por Mês e Ano (Tendência)
receita_mes_ano_desc = (validos.groupby(['ano', 'mes'])['receita']
                 .sum() # Somar todos os itens de uma categoria
                 .sort_values(ascending=False)
                 )
receita_mes_ano_desc

ano   mes
2018  5      59838.74
      4      54012.93
      3      53675.68
      1      52377.37
      8      52128.30
2017  11     49199.09
2018  6      44201.92
      7      43567.85
      2      43368.86
2017  12     39069.70
      10     33937.19
      8      32595.76
      9      27969.33
      7      27579.68
      6      26044.67
      3      25153.77
      5      23151.18
      4      18119.38
      2       9473.58
      1       5027.67
2016  10      2097.64
Name: receita, dtype: float64